name: Build

on:
  pull_request:
    branches: [ development, staging, production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.14.2
        registry-url: https://registry.npmjs.org/
    - name: Install dependencies
      run: npm i
    - name: Run linter
      run: npm run lint
    - name: Run build
      run: npm run build

