name: Development

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          registry-url: https://registry.npmjs.org/
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      -
        name: Get tag
        id: tag_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build app
        uses: actions/checkout@master
        with:
          repository: nibdo/bloben-tasks
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bloben/tasks:development
